#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
	/usr/sbin/router-banner apply >/dev/null 2>&1
}

stop_service() {
	return 0
}

reload_service() {
	/usr/sbin/router-banner apply >/dev/null 2>&1
}

service_triggers() {
	procd_add_reload_trigger router_banner
}

uninstall() {
	/usr/sbin/router-banner restore
}
